In [1]:
import numpy as np

# Параметры
n = 10                     # количество агентов
eps = 1e-6                 # точность сходимости
max_iter = 1000            # максимальное число итераций

# Генерация стохастической матрицы доверия
np.random.seed(42)         # для воспроизводимости
A = np.random.rand(n, n)
A = A / A.sum(axis=1, keepdims=True)

print("Матрица доверия A (стохастическая по строкам):")
print(np.round(A, 4))

# Моделирование без управления
x0_neutral = np.random.rand(n)          # начальные мнения
print("\nНачальные мнения (без управления):", np.round(x0_neutral, 3))

x = x0_neutral.copy()
for t in range(max_iter):
    x_new = A @ x
    if np.max(np.abs(x_new - x)) < eps:
        break
    x = x_new

print(f"Сходимость за {t+1} итераций.")
print("Итоговое мнение (без управления):", np.round(x, 4))

# Моделирование с информационным управлением
# Выбор непересекающихся множеств агентов для двух игроков
all_agents = set(range(n))
F = set(np.random.choice(n, size=2, replace=False))   # 2 агента для первого игрока
remaining = all_agents - F
S = set(np.random.choice(list(remaining), size=2, replace=False))  # 2 агента для второго
neutral = all_agents - F - S

# Управляющие воздействия
u = np.random.uniform(0, 100)      # для первого игрока (положительное)
v = np.random.uniform(-100, 0)     # для второго игрока (отрицательное)

# Начальные мнения с учётом управлений
x0_control = np.zeros(n)
for i in neutral:
    x0_control[i] = np.random.rand()          # нейтральные – случайные [0,1]
for i in F:
    x0_control[i] = u
for i in S:
    x0_control[i] = v

print("\n--- Информационное противоборство ---")
print(f"Агенты первого игрока (F): {sorted(F)} -> управление u = {u:.3f}")
print(f"Агенты второго игрока (S): {sorted(S)} -> управление v = {v:.3f}")
print(f"Нейтральные агенты: {sorted(neutral)}")
print("Начальные мнения с управлением:", np.round(x0_control, 3))

x = x0_control.copy()
for t in range(max_iter):
    x_new = A @ x
    if np.max(np.abs(x_new - x)) < eps:
        break
    x = x_new

print(f"Сходимость за {t+1} итераций.")
print("Итоговое мнение (с управлением):", np.round(x, 4))

Матрица доверия A (стохастическая по строкам):
[[0.072  0.1828 0.1407 0.1151 0.03   0.03   0.0112 0.1665 0.1156 0.1361]
 [0.0052 0.2454 0.2106 0.0537 0.046  0.0464 0.077  0.1328 0.1093 0.0737]
 [0.1528 0.0348 0.073  0.0915 0.1139 0.1961 0.0499 0.1284 0.148  0.0116]
 [0.1193 0.0335 0.0128 0.1863 0.1896 0.1587 0.0598 0.0192 0.1344 0.0864]
 [0.0302 0.1224 0.0085 0.2248 0.064  0.1638 0.077  0.1286 0.1351 0.0457]
 [0.1685 0.1347 0.1633 0.1555 0.1039 0.1602 0.0154 0.0341 0.0079 0.0565]
 [0.0832 0.0581 0.1773 0.0763 0.0601 0.1161 0.0302 0.1716 0.016  0.2112]
 [0.1698 0.0437 0.0012 0.1793 0.1554 0.1603 0.1696 0.0163 0.0788 0.0255]
 [0.1646 0.1189 0.0631 0.0121 0.0593 0.062  0.1391 0.1216 0.1692 0.0901]
 [0.0266 0.1584 0.1689 0.1246 0.1712 0.1097 0.1161 0.0949 0.0056 0.024 ]]

Начальные мнения (без управления): [0.031 0.636 0.314 0.509 0.908 0.249 0.41  0.756 0.229 0.077]
Сходимость за 9 итераций.
Итоговое мнение (без управления): [0.4221 0.4221 0.4221 0.4221 0.4221 0.4221 0.4221 0.4221 0.4221 